import { UserPropFilter } from '../../types/prop-filter'

export const PublicUserProps: UserPropFilter = {
  id: true,
  firstName: true,
  lastName: true,
  picture: true,
  email: true,
  gender: true,
  location: true,
  role: true,
  bio: true,
  language: true,
  title: true,
  socialMedia: true,
  loginCount: true,
  hasProfileSet: true,
  organization: true,
  tags: true,
  skills: true,
  status: true,
  education: true,
}

export const AdminUserProps: UserPropFilter = {
  id: true,
  firstName: true,
  lastName: true,
  picture: true,
  email: true,
  gender: true,
  phone: true,
  location: true,
  role: true,
  bio: true,
  language: true,
  title: true,
  socialMedia: true,
  googleID: true,
  loginCount: true,
  hasProfileSet: true,
  organization: true,
  tags: true,
  skills: true,
  status: true,
  education: true,
}
